//
//  MockEventData.swift
//  spotmatch
//
//  Created by Chris Jones on 5/21/24.
//

import Foundation
import SwiftUI

let sampleUsers = [
    User(name: "Chris", location: .testLocationAtlanta),
    User(name: "John", location: .testLocationCupertino),
    User(name: "Jane", location: .testLocationAtlanta),
    User(name: "Alice", location: .testLocationCupertino),
    User(name: "Bob", location: .testLocationAtlanta),
    User(name: "Jill", location: .testLocationCupertino),
    User(name: "Bill", location: .testLocationAtlanta)
]

let sampleWorkout = Workout(
    name: "Full Body Workout",
    exercises: [
        Exercise(name: "HIGH KNEES", duration: 20, oneRM: "N/A", reps: "10-12", rest: "20 sec.", type: .cardio, creator: sampleUsers[0]),
        Exercise(name: "SQUATS", duration: 45, oneRM: "100 kg", reps: "8-10", rest: "30 sec.", type: .strength, creator: sampleUsers[0]),
        Exercise(name: "PLANK", duration: 60, oneRM: "N/A", reps: "N/A", rest: "60 sec.", type: .flexibility, creator: sampleUsers[0])
    ],
    duration: 25.0,
    intensity: .medium,
    muscle: "Full Body"
)

let sampleEvent = Event(
    startDate: Date(),
    endDate: Date(),
    duration: 1.0,
    language: "English",
    title: "Morning Yoga",
    time: "08:00 AM",
    location: EventLocation(
        name: "Apple Park Visitor Center",
        city: "Cupertino",
        state: "California",
        country: "USA",
        latitude: 37.333744,
        longitude: -122.009056
    ),
    attendees: [sampleUsers[0], sampleUsers[1], sampleUsers[2]],
    reoccurring: false,
    weekdays: [.monday],
    workout: sampleWorkout,
    type: .publicEvent,
    facilitationType: .trainer,
    participantLimit: 20,
    description: "Lorem ipsum dolor sit amet consectetur. Lacus posuere odio enim ultrices placerat amet a nisl. Ipsum tristique purus ut egestas lectus semper ac. Consectetur in aliquet cursus urna hac lacus id hac.",
    itemsToBring: ["Yoga mat", "Water bottle"],
    images: ["yoga1"],
    organizer: sampleUsers[0],
    eventTags: ["Yoga", "Morning", "Relaxing"],
    eventGoal: .flexibility
)

let sampleEvents = [
    Event(
        startDate: Date(),
        endDate: Date().addingTimeInterval(3600),
        duration: 1.0,
        language: "English",
        title: "Sunrise Stretch",
        time: "06:00 AM",
        location: EventLocation(
            name: "Cupertino City Park",
            city: "Cupertino",
            state: "California",
            country: "USA",
            latitude: 37.333744,
            longitude: -122.009056
        ),
        attendees: [sampleUsers[0], sampleUsers[2]],
        reoccurring: true,
        weekdays: [.monday, .wednesday, .friday],
        workout: sampleWorkout,
        type: .publicEvent,
        facilitationType: .trainer,
        participantLimit: 15,
        description: "Start your day with a full-body stretch session.",
        itemsToBring: ["Yoga mat", "Water bottle"],
        images: ["stretch1"],
        organizer: sampleUsers[0],
        eventTags: ["Stretching", "Morning", "Flexibility"],
        eventGoal: .flexibility
    ),
    Event(
        startDate: Date().addingTimeInterval(7200),
        endDate: Date().addingTimeInterval(10800),
        duration: 1.0,
        language: "English",
        title: "Core Conditioning",
        time: "08:00 AM",
        location: EventLocation(
            name: "De Anza College Track",
            city: "Cupertino",
            state: "California",
            country: "USA",
            latitude: 37.331256,
            longitude: -122.029639
        ),
        attendees: [sampleUsers[1], sampleUsers[3]],
        reoccurring: true,
        weekdays: [.tuesday, .thursday],
        workout: sampleWorkout,
        type: .publicEvent,
        facilitationType: .trainer,
        participantLimit: 20,
        description: "Strengthen your core muscles in this intensive session.",
        itemsToBring: ["Yoga mat", "Towel"],
        images: ["core1"],
        organizer: sampleUsers[1],
        eventTags: ["Core", "Strength", "Conditioning"],
        eventGoal: .strength
    ),
    Event(
        startDate: Date().addingTimeInterval(10800),
        endDate: Date().addingTimeInterval(14400),
        duration: 1.0,
        language: "English",
        title: "Morning Run Club",
        time: "09:00 AM",
        location: EventLocation(
            name: "Stevens Creek Trail",
            city: "Mountain View",
            state: "California",
            country: "USA",
            latitude: 37.386052,
            longitude: -122.083851
        ),
        attendees: [sampleUsers[2],],
        reoccurring: true,
        weekdays: [.saturday],
        workout: sampleWorkout,
        type: .publicEvent,
        facilitationType: .trainer,
        participantLimit: 30,
        description: "Join us for a morning run along the scenic trail.",
        itemsToBring: ["Running shoes", "Water bottle"],
        images: ["run1"],
        organizer: sampleUsers[2],
        eventTags: ["Running", "Cardio", "Aerobics"],
        eventGoal: .aerobics
    ),
    Event(
        startDate: Date().addingTimeInterval(14400),
        endDate: Date().addingTimeInterval(18000),
        duration: 1.0,
        language: "English",
        title: "Power Yoga",
        time: "11:00 AM",
        location: EventLocation(
            name: "YogaWorks",
            city: "Sunnyvale",
            state: "California",
            country: "USA",
            latitude: 37.36883,
            longitude: -122.03635
        ),
        attendees: [sampleUsers[0], sampleUsers[2], sampleUsers[3]],
        reoccurring: true,
        weekdays: [.monday, .wednesday],
        workout: sampleWorkout,
        type: .publicEvent,
        facilitationType: .trainer,
        participantLimit: 15,
        description: "Energize your body and mind with Power Yoga.",
        itemsToBring: ["Yoga mat", "Towel"],
        images: ["yoga2"],
        organizer: sampleUsers[0],
        eventTags: ["Yoga", "Power", "Flexibility"],
        eventGoal: .flexibility
    ),
    Event(
        startDate: Date().addingTimeInterval(18000),
        endDate: Date().addingTimeInterval(21600),
        duration: 1.0,
        language: "English",
        title: "Strength Training Basics",
        time: "12:00 PM",
        location: EventLocation(
            name: "24 Hour Fitness",
            city: "Santa Clara",
            state: "California",
            country: "USA",
            latitude: 37.354107,
            longitude: -121.955238
        ),
        attendees: [sampleUsers[1], sampleUsers[3]],
        reoccurring: true,
        weekdays: [.tuesday, .thursday],
        workout: sampleWorkout,
        type: .publicEvent,
        facilitationType: .trainer,
        participantLimit: 20,
        description: "Learn the fundamentals of strength training.",
        itemsToBring: ["Gym clothes", "Water bottle"],
        images: ["strength1"],
        organizer: sampleUsers[1],
        eventTags: ["Strength", "Training", "Basics"],
        eventGoal: .strength
    ),
    Event(
        startDate: Date().addingTimeInterval(21600),
        endDate: Date().addingTimeInterval(25200),
        duration: 1.0,
        language: "English",
        title: "Evening Zumba",
        time: "06:00 PM",
        location: EventLocation(
            name: "Cupertino Community Center",
            city: "Cupertino",
            state: "California",
            country: "USA",
            latitude: 37.322998,
            longitude: -122.032182
        ),
        attendees: [sampleUsers[2], sampleUsers[4]],
        reoccurring: true,
        weekdays: [.monday, .wednesday],
        workout: sampleWorkout,
        type: .publicEvent,
        facilitationType: .trainer,
        participantLimit: 25,
        description: "Dance your way to fitness with evening Zumba.",
        itemsToBring: ["Water bottle", "Towel"],
        images: ["zumba1"],
        organizer: sampleUsers[2],
        eventTags: ["Zumba", "Dance", "Aerobics"],
        eventGoal: .aerobics
    ),
    Event(
        startDate: Date().addingTimeInterval(25200),
        endDate: Date().addingTimeInterval(28800),
        duration: 1.0,
        language: "English",
        title: "Pilates for Beginners",
        time: "07:00 PM",
        location: EventLocation(
            name: "Pilates Studio",
            city: "Palo Alto",
            state: "California",
            country: "USA",
            latitude: 37.441883,
            longitude: -122.143019
        ),
        attendees: [sampleUsers[3], sampleUsers[0]],
        reoccurring: true,
        weekdays: [.tuesday, .thursday],
        workout: sampleWorkout,
        type: .publicEvent,
        facilitationType: .trainer,
        participantLimit: 10,
        description: "Learn Pilates techniques to improve your flexibility.",
        itemsToBring: ["Yoga mat", "Towel"],
        images: ["pilates1"],
        organizer: sampleUsers[3],
        eventTags: ["Pilates", "Flexibility", "Beginner"],
        eventGoal: .flexibility
    ),
    Event(
        startDate: Date().addingTimeInterval(28800),
        endDate: Date().addingTimeInterval(32400),
        duration: 1.0,
        language: "English",
        title: "Cycling Club",
        time: "08:00 PM",
        location: EventLocation(
            name: "Los Gatos Creek Trail",
            city: "Los Gatos",
            state: "California",
            country: "USA",
            latitude: 37.235808,
            longitude: -121.962374
        ),
        attendees: [sampleUsers[4], sampleUsers[1]],
        reoccurring: true,
        weekdays: [.saturday],
        workout: sampleWorkout,
        type: .publicEvent,
        facilitationType: .trainer,
        participantLimit: 30,
        description: "Join our cycling club for an evening ride.",
        itemsToBring: ["Bike", "Helmet", "Water bottle"],
        images: ["cycling1"],
        organizer: sampleUsers[4],
        eventTags: ["Cycling", "Cardio", "Outdoor"],
        eventGoal: .aerobics
    ),
    Event(
        startDate: Date().addingTimeInterval(32400),
        endDate: Date().addingTimeInterval(36000),
        duration: 1.0,
        language: "English",
        title: "Sunset Meditation",
        time: "09:00 PM",
        location: EventLocation(
            name: "Shoreline Park",
            city: "Mountain View",
            state: "California",
            country: "USA",
            latitude: 37.430733,
            longitude: -122.087507
        ),
        attendees: [sampleUsers[0], sampleUsers[2], sampleUsers[3]],
        reoccurring: false,
        weekdays: [.sunday],
        workout: sampleWorkout,
        type: .publicEvent,
        facilitationType: .trainer,
        participantLimit: 20,
        description: "Relax and meditate as the sun sets.",
        itemsToBring: ["Yoga mat", "Comfortable clothes"],
        images: ["meditation1"],
        organizer: sampleUsers[0],
        eventTags: ["Meditation", "Relaxation", "Evening"],
        eventGoal: .mobility
    ),
    Event(
        startDate: Date().addingTimeInterval(36000),
        endDate: Date().addingTimeInterval(39600),
        duration: 1.0,
        language: "English",
        title: "HIIT Bootcamp",
        time: "10:00 PM",
        location: EventLocation(
            name: "Athletic Performance Center",
            city: "San Jose",
            state: "California",
            country: "USA",
            latitude: 37.338208,
            longitude: -121.886329
        ),
        attendees: [sampleUsers[1], sampleUsers[3], sampleUsers[4]],
        reoccurring: true,
        weekdays: [.monday, .wednesday],
        workout: sampleWorkout,
        type: .publicEvent,
        facilitationType: .trainer,
        participantLimit: 20,
        description: "Intense HIIT workout to burn calories and build endurance.",
        itemsToBring: ["Water bottle", "Towel"],
        images: ["hiit2"],
        organizer: sampleUsers[1],
        eventTags: ["HIIT", "Cardio", "Bootcamp"],
        eventGoal: .aerobics
    ),
    Event(
        startDate: Date().addingTimeInterval(39600),
        endDate: Date().addingTimeInterval(43200),
        duration: 1.0,
        language: "English",
        title: "Functional Training",
        time: "11:00 PM",
        location: EventLocation(
            name: "Fitness Evolution",
            city: "Fremont",
            state: "California",
            country: "USA",
            latitude: 37.548271,
            longitude: -121.988571
        ),
        attendees: [sampleUsers[2], sampleUsers[4]],
        reoccurring: true,
        weekdays: [.tuesday, .thursday],
        workout: sampleWorkout,
        type: .publicEvent,
        facilitationType: .trainer,
        participantLimit: 15,
        description: "Enhance your functional strength and mobility.",
        itemsToBring: ["Gym clothes", "Water bottle"],
        images: ["functional1"],
        organizer: sampleUsers[2],
        eventTags: ["Functional", "Strength", "Training"],
        eventGoal: .strength
    ),
    Event(
        startDate: Date().addingTimeInterval(43200),
        endDate: Date().addingTimeInterval(46800),
        duration: 1.0,
        language: "English",
        title: "Beach Volleyball",
        time: "12:00 AM",
        location: EventLocation(
            name: "Santa Cruz Beach",
            city: "Santa Cruz",
            state: "California",
            country: "USA",
            latitude: 36.974117,
            longitude: -122.030792
        ),
        attendees: [sampleUsers[3], sampleUsers[0], sampleUsers[1]],
        reoccurring: false,
        weekdays: [.sunday],
        workout: sampleWorkout,
        type: .publicEvent,
        facilitationType: .trainer,
        participantLimit: 20,
        description: "Join us for a fun beach volleyball session.",
        itemsToBring: ["Beach attire", "Sunscreen"],
        images: ["volleyball1"],
        organizer: sampleUsers[3],
        eventTags: ["Volleyball", "Beach", "Aerobics"],
        eventGoal: .aerobics
    ),
    Event(
        startDate: Date().addingTimeInterval(46800),
        endDate: Date().addingTimeInterval(50400),
        duration: 1.0,
        language: "English",
        title: "Kettlebell Workout",
        time: "01:00 AM",
        location: EventLocation(
            name: "Bay Area Gym",
            city: "Oakland",
            state: "California",
            country: "USA",
            latitude: 37.804364,
            longitude: -122.271114
        ),
        attendees: [sampleUsers[4], sampleUsers[2]],
        reoccurring: true,
        weekdays: [.monday, .wednesday],
        workout: sampleWorkout,
        type: .publicEvent,
        facilitationType: .trainer,
        participantLimit: 15,
        description: "Full-body kettlebell workout to build strength and endurance.",
        itemsToBring: ["Gym clothes", "Water bottle"],
        images: ["kettlebell1"],
        organizer: sampleUsers[4],
        eventTags: ["Kettlebell", "Strength", "Full-body"],
        eventGoal: .strength
    ),
    Event(
        startDate: Date().addingTimeInterval(50400),
        endDate: Date().addingTimeInterval(54000),
        duration: 1.0,
        language: "English",
        title: "Boxing Fundamentals",
        time: "02:00 AM",
        location: EventLocation(
            name: "Title Boxing Club",
            city: "San Francisco",
            state: "California",
            country: "USA",
            latitude: 37.774929,
            longitude: -122.419416
        ),
        attendees: [sampleUsers[0], sampleUsers[1]],
        reoccurring: true,
        weekdays: [.tuesday, .thursday],
        workout: sampleWorkout,
        type: .publicEvent,
        facilitationType: .trainer,
        participantLimit: 20,
        description: "Learn the basics of boxing in a fun and energetic class.",
        itemsToBring: ["Boxing gloves", "Hand wraps"],
        images: ["boxing1"],
        organizer: sampleUsers[0],
        eventTags: ["Boxing", "Cardio", "Skills"],
        eventGoal: .aerobics
    ),
    Event(
        startDate: Date().addingTimeInterval(54000),
        endDate: Date().addingTimeInterval(57600),
        duration: 1.0,
        language: "English",
        title: "Advanced Yoga",
        time: "03:00 AM",
        location: EventLocation(
            name: "Bliss Yoga Studio",
            city: "San Mateo",
            state: "California",
            country: "USA",
            latitude: 37.562992,
            longitude: -122.325525
        ),
        attendees: [sampleUsers[1], sampleUsers[3]],
        reoccurring: true,
        weekdays: [.monday, .wednesday],
        workout: sampleWorkout,
        type: .publicEvent,
        facilitationType: .trainer,
        participantLimit: 10,
        description: "Challenge yourself with advanced yoga poses and techniques.",
        itemsToBring: ["Yoga mat", "Towel"],
        images: ["yoga3"],
        organizer: sampleUsers[1],
        eventTags: ["Yoga", "Advanced", "Flexibility"],
        eventGoal: .flexibility
    ),
    Event(
        startDate: Date().addingTimeInterval(57600),
        endDate: Date().addingTimeInterval(61200),
        duration: 1.0,
        language: "English",
        title: "Bootcamp Circuit",
        time: "04:00 AM",
        location: EventLocation(
            name: "Golden Gate Park",
            city: "San Francisco",
            state: "California",
            country: "USA",
            latitude: 37.769040,
            longitude: -122.483519
        ),
        attendees: [sampleUsers[2], sampleUsers[4]],
        reoccurring: true,
        weekdays: [.tuesday, .thursday],
        workout: sampleWorkout,
        type: .publicEvent,
        facilitationType: .trainer,
        participantLimit: 25,
        description: "High-energy circuit training for all fitness levels.",
        itemsToBring: ["Water bottle", "Towel"],
        images: ["bootcamp1"],
        organizer: sampleUsers[2],
        eventTags: ["Bootcamp", "Circuit", "Fitness"],
        eventGoal: .strength
    ),
    Event(
        startDate: Date().addingTimeInterval(61200),
        endDate: Date().addingTimeInterval(64800),
        duration: 1.0,
        language: "English",
        title: "Swimming Clinic",
        time: "05:00 AM",
        location: EventLocation(
            name: "Sunnyvale Swim Complex",
            city: "Sunnyvale",
            state: "California",
            country: "USA",
            latitude: 37.36883,
            longitude: -122.03635
        ),
        attendees: [sampleUsers[3], sampleUsers[0]],
        reoccurring: true,
        weekdays: [.monday, .wednesday],
        workout: sampleWorkout,
        type: .publicEvent,
        facilitationType: .trainer,
        participantLimit: 20,
        description: "Improve your swimming technique and endurance.",
        itemsToBring: ["Swimsuit", "Towel", "Goggles"],
        images: ["swimming1"],
        organizer: sampleUsers[3],
        eventTags: ["Swimming", "Water", "Fitness"],
        eventGoal: .aerobics
    ),
    Event(
        startDate: Date().addingTimeInterval(64800),
        endDate: Date().addingTimeInterval(68400),
        duration: 1.0,
        language: "English",
        title: "Martial Arts Training",
        time: "06:00 AM",
        location: EventLocation(
            name: "Dojo Martial Arts",
            city: "Santa Clara",
            state: "California",
            country: "USA",
            latitude: 37.354107,
            longitude: -121.955238
        ),
        attendees: [sampleUsers[4], sampleUsers[2], sampleUsers[3]],
        reoccurring: true,
        weekdays: [.tuesday, .thursday],
        workout: sampleWorkout,
        type: .publicEvent,
        facilitationType: .trainer,
        participantLimit: 15,
        description: "Develop skills and discipline in martial arts training.",
        itemsToBring: ["Gi", "Belt", "Water bottle"],
        images: ["martialarts1"],
        organizer: sampleUsers[4],
        eventTags: ["Martial Arts", "Discipline", "Training"],
        eventGoal: .strength
    ),
    Event(
        startDate: Date().addingTimeInterval(68400),
        endDate: Date().addingTimeInterval(72000),
        duration: 1.0,
        language: "English",
        title: "Morning Meditation",
        time: "07:00 AM",
        location: EventLocation(
            name: "Cupertino Community Center",
            city: "Cupertino",
            state: "California",
            country: "USA",
            latitude: 37.322998,
            longitude: -122.032182
        ),
        attendees: [sampleUsers[0], sampleUsers[1]],
        reoccurring: true,
        weekdays: [.monday, .friday],
        workout: sampleWorkout,
        type: .publicEvent,
        facilitationType: .trainer,
        participantLimit: 20,
        description: "Start your day with guided meditation to enhance your focus.",
        itemsToBring: ["Yoga mat", "Comfortable clothes"],
        images: ["meditation2"],
        organizer: sampleUsers[0],
        eventTags: ["Meditation", "Mindfulness", "Morning"],
        eventGoal: .mobility
    )
]
